force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <label>Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerrUser__c/TerrUser__c.object-meta.xml
<CustomObject>
    <label>TerrUser</label>
    <nameField>
        <label>TerrUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerrUser</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TerrUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>TerrUser</relationshipLabel>
    <relationshipName>TerrUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DefineTriggersTest.cls
@IsTest
public with sharing class DefineTriggersTest {
    @IsTest
    private static void checkExistenceOfTriggers() {
        List<String>objectNames = new List<String>{
                'Account','Territory__c','Reference__c','TerrUser__c'
        };
        List<AggregateResult>aggregateResults = [
                SELECT TableEnumOrId, Count(Id)
                FROM ApexTrigger
                WHERE TableEnumOrId IN:objectNames
                GROUP BY TableEnumOrId
        ];
        System.assertEquals(objectNames.size(),aggregateResults.size(),'There are  no triggers for all object in list');
    }
}