force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <label>Reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reference</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reference</relationshipLabel>
    <relationshipName>Reference</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reference</relationshipLabel>
    <relationshipName>Reference</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerrUser__c/TerrUser__c.object-meta.xml
<CustomObject>
    <label>TerrUser</label>
    <nameField>
        <label>TerrUser Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerrUser</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TerrUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>TerrUser</relationshipLabel>
    <relationshipName>TerrUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerrUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerrUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataService.cls
@isTest
public with sharing class TestDataService {
    // todo rename `get` to `create`
    public static User createUserForTest(String ComNicknameAndUsername) {

        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name='TerritoryUser' LIMIT 1 ];

        User u = new user();
        u.LastName = 'Test Code1';
        u.Email = 'test@test.com';
        u.Alias = 'Tcode';
        u.Username = ComNicknameAndUsername;
        u.CommunityNickname = ComNicknameAndUsername;
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'GMT';
        u.ProfileID = profiles[0].id;
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';

        insert u;

        return u;
    }
//    public static Territory__c getTerritoryForTest (String name,Territory__c territory) {
//        Territory__c terr = new Territory__c(Name=name,Territory__c=territory.id);
//        insert terr;
//        return terr;
//    }
    public static Territory__c createTerritoryForTest(String name,Id territory) {
        Territory__c terr = new Territory__c(Name=name,Territory__c=territory);
        insert terr;
        return terr;
    }
    public static Territory__c createTerritoryForTest(String name) {
        Territory__c terr = new Territory__c(Name=name);
        insert terr;
        return terr;
    }
    public static  TerrUser__c createTerrUserForTest(String name,Id territory,Id user){
        TerrUser__c terUser = new TerrUser__c (Name=name,Territory__c=territory,User__c=user);
        insert terUser;
        return terUser;
    }
    public static  List<Account> createAccountsWithTerritoryForTest(Integer countAccounts,String name,Id territory) {
        List <Account> accounts = new List<Account>();
        for(Integer i=0;i<countAccounts;i++) {
            Account acc = new Account();
            acc.Name = i+name;
            acc.Territory__c = territory;
            accounts.add(acc);
        }
        insert accounts;
        return accounts;
    }
    public static  List<Contact> createContactsForTest(Integer countContacts,String lastName) {
        List <Contact> contacts = new List<Contact>();
        for(Integer i=0;i<countContacts;i++) {
            Contact cont = new Contact();
            cont.LastName = lastName;
            contacts.add(cont);
        }
        insert contacts;
        return contacts;
    }
    public static Reference__c createReferenceForTest(String name,Account acc,Contact cont) {
        Reference__c ref = new Reference__c (Name=name,Account__c=acc.Id,Contact__c=cont.Id);
        insert ref;
        return ref;
    }
    public static List<User> createUsersForTest(Integer countUsers,String ComNicknameAndUsername) {

        List<Profile> profiles = [SELECT Id FROM Profile WHERE Name='TerritoryUser' LIMIT 1 ];

        List<User> users = new List<User>();

        for(Integer i=0;i<countUsers;i++) {
            User u = new user();
            u.LastName = i+'Test Code1';
            u.Email = 'test@test.com';
            u.Alias = i+'Tcode';
            u.Username = i+ComNicknameAndUsername;
            u.CommunityNickname = i+ComNicknameAndUsername;
            u.LocaleSidKey = 'en_US';
            u.TimeZoneSidKey = 'GMT';
            u.ProfileID = profiles[0].id;
            u.LanguageLocaleKey = 'en_US';
            u.EmailEncodingKey = 'UTF-8';
            users.add(u);
        }

        insert users;

        return users;
    }
}